### ISSUE TITLE
php 7: Methods with the same name as their class will not be constructors in a future version of PHP

### ISSUE THREAD

**Issue by vincentvis** [croxton/Switchee#11]
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Switchee has a deprecated constructor in /home/deb11866n8/domains/ruim-barneveld-d-o-t-nl.alvast-online.nl/system/user/addons/switchee/pi.switchee.php on line 12

according to: http://php.net/manual/en/migration70.deprecated.php
__constructor() functions are not affected

If I edit line 26 to `public function __construct()` the error is gone.
But I'm not sure what implications this has.. 
I've tested with simple single {exp:switchee} in my templates and with case with a nested switchee. Both seem to work.
I've only tested on php 7.0.7. So it could be that this breaks older versions.. (not sure)

**Comment by croxton** [comment]
Yes safe to change that line as you have. I'll change it in the repo.
