### ISSUE TITLE
parameter variable='0' fails (fetch_param bug)

### ISSUE THREAD

**Issue by GDmac** [croxton/Switchee#12]
Probably due to the way how template vars are now more type-aware (bool,int,empty string)
and the way how switchee fetches the template var, Switchee fails on the following (in newer EE)

```
{exp:switchee variable="0"}
  {case value="0"}
    variable is zero
  {/case}
  {case default="yes"}
    failboat
  {/case}
{/exp:switchee}

// result: failboat
```

https://github.com/croxton/Switchee/blob/develop/pi.switchee.php#L42
```
$var = ee()->TMPL->fetch_param('variable') ? ee()->TMPL->fetch_param('variable') : '';
```
Template fetch_param supports a default value in its second parameter,
the following makes it work again
```
$var = ee()->TMPL->fetch_param('variable', '')
```

**Comment by croxton** [comment]
In older versions of EE there was no way to send "1" or "0" as parameters, they got converted to "y" and "n". Not sure if that is still the case, but no matter.

Did you want to put in a PR for that minor change? Cheers.

**Comment by GDmac** [comment]
Hmm, i was updating an older site, and now see that i did 
hack in member variables into switchee so it could do 
variable="{logged_in}" with a case=0. PR under way
