### ISSUE TITLE
Example Pagination Expression on Devot.ee not working

### ISSUE THREAD

**Issue by amityweb** [croxton/Switchee#4]
This is not an issue with the code, but the forum on Devot.ee doesn't allow me to post...

On your devot.ee example, the expression for pagination is not working for me, whereas in your forum you post a slightly different one which does:

Devot.ee Example, not working:-
 {case value="#^P(\\d+)$#|''"}

Devot.ee Forum, working:-
{case value = "#^P(\d+)$#|''"}

I think its just an extra backslash. Maybe devot.ee would not allow a single one? Whatever the resson had me stumped for ages so I think it should be fixed or noted.

**Comment by amityweb** [comment]
Probably an escape issue, I had to enter the backslash three times above in order to show twice! Probably similar thing on Devot.ee

**Comment by croxton** [comment]
Hi yes devot:ee adds an extra backslash; I've told them but they haven't fixed it yet!

**Comment by MobsterGit** [comment]
I would also like to verify in EE3 
`{case value="#^P(\d+)$#|''"}`
works with 3 segments discussed [here](https://devot-ee.com/add-ons/support/switchee/viewthread/12960).  Thanks for pointing this out!
