### ISSUE TITLE
Switching on playa total_children

### ISSUE THREAD

**Issue by russback** [croxton/Switchee#5]
Hey Mark

Is there something wrong with the following? There is a Playa field (component_3) within a Matrix (components) row so I want to detect if an entry is selected:

```
{components}

    {exp:switchee variable="{component_3:total_children}" parse="inward"}

        {case "1"}
            selected
        {/case}

        {case default='Yes'}
            nada
        {/case}

    {/exp:switchee} 

{/components}
```

I just get nada output every time, even though I can see that the total_children tag evaluates to 1.

Is this a parse order issue?

**Comment by russback** [comment]
Sorry, ignore that - found an issue elsewhere.

**Comment by croxton** [comment]
OK, but just so you are aware the case syntax you used was wrong:

```
{case value="1"}
...
{/case}
```

**Comment by russback** [comment]
Thanks, Mark. I was using the wrong Playa tag but now I've got that playa tag working with a regular IF/ELSE conditional, it still fails for me when using Switchee, specifically this:

```
{components}

    {exp:switchee variable="{exp:playa:total_children col='component_3' row_id='{row_id}'}" parse="inward"}

        {case value="1"}
            double
        {/case}

        {case default='Yes'}
            single
        {/case}

    {/exp:switchee} 

{/components}
```

As a regular conditional it's fine:

```
{if '{exp:playa:total_children col="component_3" row_id="{row_id}"}' == "1"}

    selected

{if:else}

    nada

{/if}
```

Error in syntax, or just not possible with Playa?

**Comment by croxton** [comment]
Ah yes EE converts '1' to 'y' when passed as a parameter (it thinks it's a boolean - same problem with '0')). You can surround it with some arbitary string to prevent this, e.g.:

```
{exp:switchee variable="/{exp:playa:total_children col='component_3' row_id='{row_id}'}/" parse="inward"}

    {case value="/1/"}
```

**Comment by russback** [comment]
Sorry Mark - spotted that I was using 'var' instead of 'variable' and now it works without the change you suggested!

**Comment by croxton** [comment]
It does? Could you tell me what version of EE are you using?

**Comment by russback** [comment]
This is on 2.7.2. Interestingly, case value="1" works OK but case value="0", regardless of whether I use a '/' to surround the value.

**Comment by russback** [comment]
That's just with a simple output of text. When I then put some code inside the case statement however, I get another error:

```
{exp:switchee variable='{exp:playa:total_children col="component_2" row_id="{row_id}"}' parse="inward"}

    {case value="1"}

        selected

    {/case}

    {case default="Yes"}

        nada

        {component_1 
            disable="pagination|member_data|trackbacks|category_fields"
        }

            {sn_component}

        {/component_1}

    {/case}

{/exp:switchee}
```

Results in this variations of this output to the template:

```
{/playabSujHqTV:categories} {/exp:playa:children} {/case} {/exp:switchee}
selected {/playatQ9yquYP:categories} {/exp:playa:children} {/case} {/exp:switchee}
```

**Comment by croxton** [comment]
Bugger, they must have changed this.

**Comment by croxton** [comment]
You'll need to use real `{exp:playa:children}` tags not the variable pairs.

**Comment by russback** [comment]
That got me a little farther but to make matters more confusing I have another switchee in that sn_component snippet, so effectively an embedded switchee (I've set a hardcoded variable of "image" just to simplify it):

```
{switchee variable="image" parse="inward"}

    {case value="image"}

        match

    {/case}

    {case default="Yes"}

        no match

    {/case}

{/switchee}
```

I now get this:

```
{switchee variable="image" parse="inward"} {case value="image"} match {/case} {case_2} no match {/case}    
{/switchee}
{switchee variable="image" parse="inward"} {case value="image"} match {/case} {case default="Yes"} no match 
{/case} {/switchee}
```

So looks like the embedded switchee isn't being parsed?

**Comment by croxton** [comment]
What's this: `{case_2}` ? Any variable that starts with 'case' is going to mess with Switchee.

**Comment by russback** [comment]
I don't know - Its output to the browser but it's not in my template code above.

**Comment by croxton** [comment]
Missing closing tag somewhere? Try adding debug="yes" to your Switchee's and see what is output to the template debugger.

**Comment by russback** [comment]
Can't see any tag problems. Can I email you the output? I'm using stash as well, so not sure if that's going to be relevant

**Comment by croxton** [comment]
Sure mcroxton at hallmark-design.co.uk

**Comment by russback** [comment]
Thanks. Sent.
