### ISSUE TITLE
stash list inside of switchee not working

### ISSUE THREAD

**Issue by alycda** [croxton/Switchee#8]
I have a single EE template, called index.html (default_site/template.group/index.html) that calls content templates (mostly based on segment 1). Some of these stash templates have very similar last segments, like segment_1/movies and segment_1/photos. I'm using switchee in the stash template to load different channels based off the last segment. I realize this might be a great use for preload replace variables, but they appear to be ignored by stash. The following does not return any results

```
{exp:switchee variable = "{segment_2}" parse="inward"}
  {case value="movies"}
    {exp:stash:set_list name="media_content" parse_tags="yes"}
      {exp:channel:entries channel="movies" limit="5"}
        {stash:item_title}{title}{/stash:item_title}
        {stash:item_summary}{summary}{/stash:item_summary}
        {stash:item_copy}{copy}{/stash:item_copy}
      {/exp:channel:entries}
    {/exp:stash:set_list}

    {exp:stash:set name="page title"}movie page title{/exp:stash:set}

  {/case}
  {case value="photos"}
    ...
  {/case}

  {case default="yes"}
    ...
  {/case}
{/exp:switchee}

...

{exp:stash:get_list name="media_content"}
<h1>{item_title} (item {count} of {absolute_results})</h1>
{/exp:stash:get_list}
```

If I remove the 'parse='inward' then I get results, but they are always the last value set, not the one that matches the switchee value I intended to match.

**Comment by croxton** [comment]
You have two `{case...}` matching the same value. You are setting a list and setting a variable, so there will be no output unless you use the tags `{exp:stash:get_list ...}` and `{exp:stash:get ...}` respectively.

**Comment by alycda** [comment]
Sorry, I copied the code incorrectly, fixed above. Also, I am using the tags you specified for retrieval, I am still only getting results if i remove `parse="inward"`.

**Comment by anchovy** [comment]
Hi 

Know this is an old post - but I'm having the same issue as alycda; no matter what the matching case is, stash is using/overwriting wirth the values in the last 'case'.

As an aside - I'm also get nothing set by stash if I use the parse="inward" option.

If you take the following code, with {page_layout_style} = '3/4':

```
{exp:switchee variable="{page_layout_style}" debug="yes"}
    {case value="3/4"}
        Case 1
        {exp:stash:set name="main_col_count"}9{/exp:stash:set}
        {exp:stash:set name="side_col_count"}3{/exp:stash:set}
    {/case}
    {case value="1/2"}
        Case 2
        {exp:stash:set name="main_col_count"}6{/exp:stash:set}
        {exp:stash:set name="side_col_count"}6{/exp:stash:set}
    {/case}
{/exp:switchee}
main_col_count = {exp:stash:get name="main_col_count"}
side_col_count = {exp:stash:get name="side_col_count"}
```

I'd expect to see (line breaks added):

```
Case 1
main_col_count = 9
side_col_count = 3
```

But what I'm seeing is:

```
Case 1
main_col_count = 6
side_col_count = 6
```

I can see in the template debugging that it's matching the correct switchee case:

```
(0.225449 / 21.81MB) Calling Class/Method: Switchee/
(0.225847 / 21.81MB) -> Class Called: Switchee
(0.225897 / 21.81MB) Switchee: evaluating variable 3/4
(0.226248 / 21.82MB) Switchee: string match: case '3/4' matched variable '3/4'
```

Any ideas?

ExpressionEngine    2.9.2 Build 20141004
Stash 2.6.2
Switchee 2.1.1

Regards
Ben

**Comment by croxton** [comment]
You absolutely do need the `parse="inward"` on the switchee. The reason the stash:get tags return nothing is parse order - they run after the stash:set because they are on the 'layer' of tags higher up in the template, and EE parses tags from the outermost layer inwards - like peeling an onion (i.e. parsing is recursive not linear). Add `process="end"` to each stash:get to make them return the expected value.
