### ISSUE TITLE
Error in PHP 5.6

### ISSUE THREAD

**Issue by johanneslamers** [croxton/Switchee#9]
A PHP Error was encountered

Severity: 8192

Message: Non-static method Switchee::usage() should not be called statically, assuming $this from incompatible context

Filename: switchee/pi.switchee.php

Line Number: 9

**Comment by GDmac** [comment]
yup, declare usage() method as `public static function usage()`

**Comment by petrov82** [comment]
on Line 280, put `public static function usage()` in place of `function usage()`

**Comment by croxton** [comment]
It is already. https://github.com/croxton/Switchee/blob/develop/pi.switchee.php#L326

What branch are you using?

**Comment by petrov82** [comment]
I went back and saw that I was using an old version. New version update is perfect, thanks!
